/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Clientes;
import javax.swing.JOptionPane;

/**
 *
 * @author Yefri Chay
 */
public class CatClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatClientes.class.getName());

    /**
     * Creates new form AbcClientes
     */
    public CatClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientesNombre = new javax.swing.JLabel();
        jLabel3Nombre = new javax.swing.JLabel();
        jTextField2Nombre = new javax.swing.JTextField();
        jLabel4Telefono = new javax.swing.JLabel();
        jLabel5Direccion = new javax.swing.JLabel();
        jLabel6Nit = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextField4Direccion = new javax.swing.JTextField();
        jTextField5Nit = new javax.swing.JTextField();
        jButton1GuardarCliente = new javax.swing.JButton();
        jLabel7Email = new javax.swing.JLabel();
        jLabel8Saldo = new javax.swing.JLabel();
        jLabel9Tipo = new javax.swing.JLabel();
        jTextField1Email = new javax.swing.JTextField();
        jTextField2Saldo = new javax.swing.JTextField();
        jTextField3Tipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clientesNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clientesNombre.setText("CATOLOGO CLIENTES");

        jLabel3Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Nombre.setText("Nombre:");

        jLabel4Telefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Telefono.setText("Telefono:");

        jLabel5Direccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5Direccion.setText("Direccion:");

        jLabel6Nit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6Nit.setText("Nit:");

        jTextField4Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4DireccionActionPerformed(evt);
            }
        });

        jTextField5Nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5NitActionPerformed(evt);
            }
        });

        jButton1GuardarCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButton1GuardarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1GuardarCliente.setText("GUARDAR");
        jButton1GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarClienteActionPerformed(evt);
            }
        });

        jLabel7Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7Email.setText("Email:");

        jLabel8Saldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8Saldo.setText("Saldo (P):");

        jLabel9Tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9Tipo.setText("Tipo:");

        jTextField1Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1EmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8Saldo)
                            .addComponent(jLabel9Tipo))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3Tipo)
                            .addComponent(jTextField2Saldo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5Direccion)
                            .addComponent(jLabel4Telefono)
                            .addComponent(jLabel6Nit)
                            .addComponent(jLabel7Email)
                            .addComponent(jLabel3Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2Nombre)
                            .addComponent(jTextField1Email)
                            .addComponent(jTextField5Nit)
                            .addComponent(jTextField4Direccion)
                            .addComponent(jTextFieldTelefono))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton1GuardarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(clientesNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(clientesNombre)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Telefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Direccion)
                    .addComponent(jTextField4Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Nit)
                    .addComponent(jTextField5Nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7Email)
                    .addComponent(jTextField1Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8Saldo)
                    .addComponent(jTextField2Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9Tipo)
                    .addComponent(jTextField3Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1GuardarCliente)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4DireccionActionPerformed

    private void jTextField5NitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5NitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5NitActionPerformed

    private void jButton1GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarClienteActionPerformed
        Clientes c = new Clientes();
        c.setNombre(jTextField2Nombre.getText());//obtener texto ingresado
        c.setTelefono(jTextFieldTelefono.getText());
        c.setDireccion(jTextField4Direccion.getText());
        c.setNit(jTextField5Nit.getText());
        c.setEmail(jTextField1Email.getText());
        try {
            float saldo = Float.parseFloat(jTextField2Saldo.getText());
            c.setSaldo_pendiente(saldo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Saldo.");
        }
        c.setTipo_cliente(jTextField3Tipo.getText());
        
        if (c.Guardar()) //variable conexion a BD
            JOptionPane.showMessageDialog(this, "Cliente Creado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Cliente NO creado", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton1GuardarClienteActionPerformed

    private void jTextField1EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientesNombre;
    private javax.swing.JButton jButton1GuardarCliente;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Telefono;
    private javax.swing.JLabel jLabel5Direccion;
    private javax.swing.JLabel jLabel6Nit;
    private javax.swing.JLabel jLabel7Email;
    private javax.swing.JLabel jLabel8Saldo;
    private javax.swing.JLabel jLabel9Tipo;
    private javax.swing.JTextField jTextField1Email;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField2Saldo;
    private javax.swing.JTextField jTextField3Tipo;
    private javax.swing.JTextField jTextField4Direccion;
    private javax.swing.JTextField jTextField5Nit;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
