/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Empleados;
import javax.swing.JOptionPane;

/**
 *
 * @author Yefri Chay
 */
public class CatEmpleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatEmpleados.class.getName());

    /**
     * Creates new form AbcEmpleados
     */
    public CatEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Guardar = new javax.swing.JButton();
        jLabel1Empleados = new javax.swing.JLabel();
        jLabel3Nombre = new javax.swing.JLabel();
        jTextField2Nombre = new javax.swing.JTextField();
        jLabel4Telefono = new javax.swing.JLabel();
        jTextField3Telefono = new javax.swing.JTextField();
        jLabel5Direccion = new javax.swing.JLabel();
        jLabel6Salario = new javax.swing.JLabel();
        jLabel7Email = new javax.swing.JLabel();
        jLabel8Puesto = new javax.swing.JLabel();
        jLabel9Jornada = new javax.swing.JLabel();
        jTextField1Direccion = new javax.swing.JTextField();
        jTextField2Salario = new javax.swing.JTextField();
        jTextField3Email = new javax.swing.JTextField();
        jTextField4Puesto = new javax.swing.JTextField();
        jTextField5Jornada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1Guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1Guardar.setText("GUARDAR");
        jButton1Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarActionPerformed(evt);
            }
        });

        jLabel1Empleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Empleados.setText("CATOLOGO EMPLEADOS");

        jLabel3Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Nombre.setText("Nombre:");

        jLabel4Telefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Telefono.setText("Telefono:");

        jLabel5Direccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5Direccion.setText("Direccion:");

        jLabel6Salario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6Salario.setText("Salario:");

        jLabel7Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7Email.setText("Email:");

        jLabel8Puesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8Puesto.setText("Puesto:");

        jLabel9Jornada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9Jornada.setText("Jornada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jLabel4Telefono)
                    .addComponent(jLabel9Jornada)
                    .addComponent(jLabel8Puesto)
                    .addComponent(jLabel7Email)
                    .addComponent(jLabel6Salario)
                    .addComponent(jLabel5Direccion))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1Empleados)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addComponent(jTextField2Nombre)
                    .addComponent(jTextField3Telefono)
                    .addComponent(jTextField2Salario)
                    .addComponent(jTextField3Email)
                    .addComponent(jTextField4Puesto)
                    .addComponent(jTextField5Jornada)
                    .addComponent(jTextField1Direccion))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Guardar)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1Empleados)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Telefono)
                    .addComponent(jTextField3Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5Direccion)
                    .addComponent(jTextField1Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6Salario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7Email))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8Puesto)
                    .addComponent(jTextField4Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5Jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9Jornada))
                .addGap(18, 18, 18)
                .addComponent(jButton1Guardar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarActionPerformed
        Empleados em = new Empleados();
        em.setNombre(jTextField2Nombre.getText());//obtener texto ingresado
        em.setTelefono(jTextField3Telefono.getText());
        em.setDireccion(jTextField1Direccion.getText());
        try {
            float salario = Float.parseFloat(jTextField2Salario.getText());
            em.setSalario(salario);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Saldo.");
        }
        em.setEmail(jTextField3Email.getText());
        em.setPuesto(jTextField4Puesto.getText());
        em.setJornada(jTextField5Jornada.getText());
        
        if (em.Guardar()) //variable conexion a BD
            JOptionPane.showMessageDialog(this, "Empleado Creado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Empleado NO creado", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Guardar;
    private javax.swing.JLabel jLabel1Empleados;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Telefono;
    private javax.swing.JLabel jLabel5Direccion;
    private javax.swing.JLabel jLabel6Salario;
    private javax.swing.JLabel jLabel7Email;
    private javax.swing.JLabel jLabel8Puesto;
    private javax.swing.JLabel jLabel9Jornada;
    private javax.swing.JTextField jTextField1Direccion;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField2Salario;
    private javax.swing.JTextField jTextField3Email;
    private javax.swing.JTextField jTextField3Telefono;
    private javax.swing.JTextField jTextField4Puesto;
    private javax.swing.JTextField jTextField5Jornada;
    // End of variables declaration//GEN-END:variables
}
