/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Inventarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Yefri Chay
 */
public class CatInventarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatInventarios.class.getName());

    /**
     * Creates new form AbcInventarios
     */
    public CatInventarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Inventarios = new javax.swing.JLabel();
        jLabel2IdInventa = new javax.swing.JLabel();
        jLabel3IdProducto = new javax.swing.JLabel();
        jButton1Generar = new javax.swing.JButton();
        jTextField1IdInven = new javax.swing.JTextField();
        jTextField2IdProduc = new javax.swing.JTextField();
        jLabel4Cantidad = new javax.swing.JLabel();
        jTextField3Cantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Inventarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1Inventarios.setText("CATALOGO INVENTARIO");

        jLabel2IdInventa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2IdInventa.setText("ID Inventario:");

        jLabel3IdProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3IdProducto.setText("ID Producto:");

        jButton1Generar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1Generar.setText("GENERAR ACCION");
        jButton1Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GenerarActionPerformed(evt);
            }
        });

        jLabel4Cantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Cantidad.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2IdInventa)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1Inventarios)
                                .addGap(0, 89, Short.MAX_VALUE))
                            .addComponent(jTextField1IdInven)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3IdProducto)
                            .addComponent(jLabel4Cantidad))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1Generar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2IdProduc)
                            .addComponent(jTextField3Cantidad))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1Inventarios)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2IdInventa)
                    .addComponent(jTextField1IdInven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3IdProducto)
                    .addComponent(jTextField2IdProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Cantidad)
                    .addComponent(jTextField3Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1Generar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GenerarActionPerformed
        Inventarios inv = new Inventarios();
        try{
            int id_i = Integer.parseInt(jTextField1IdInven.getText().trim());//obtener texto ingresado
            inv.setId_inventario(id_i);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Stock.");
            return;
        }
        try{
            int id_p = Integer.parseInt(jTextField2IdProduc.getText().trim());//obtener texto ingresado
            inv.setId_inventario(id_p);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Stock.");
            return;
        }
        try{
            int id_c = Integer.parseInt(jTextField3Cantidad.getText().trim());//obtener texto ingresado
            inv.setId_inventario(id_c);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Stock.");
            return;
        }
        
        if (inv.Generar()) //variable conexion a BD
            JOptionPane.showMessageDialog(this, "Inventario Creado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Inventario NO creado", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1GenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatInventarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Generar;
    private javax.swing.JLabel jLabel1Inventarios;
    private javax.swing.JLabel jLabel2IdInventa;
    private javax.swing.JLabel jLabel3IdProducto;
    private javax.swing.JLabel jLabel4Cantidad;
    private javax.swing.JTextField jTextField1IdInven;
    private javax.swing.JTextField jTextField2IdProduc;
    private javax.swing.JTextField jTextField3Cantidad;
    // End of variables declaration//GEN-END:variables
}
