/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Productos;
import javax.swing.JOptionPane;

/**
 *
 * @author Yefri Chay
 */
public class CatProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatProductos.class.getName());

    /**
     * Creates new form AbcProductos
     */
    public CatProductos() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Productos = new javax.swing.JLabel();
        jLabel3Nombre = new javax.swing.JLabel();
        jTextField2Nom = new javax.swing.JTextField();
        jLabel4Talla = new javax.swing.JLabel();
        jLabel5Precio = new javax.swing.JLabel();
        jButton1GuardarProduc = new javax.swing.JButton();
        jLabel6Stock = new javax.swing.JLabel();
        jLabel7Genero = new javax.swing.JLabel();
        jLabel8Categoria = new javax.swing.JLabel();
        jTextField1Stock = new javax.swing.JTextField();
        jTextField4Talla = new javax.swing.JTextField();
        jTextField5Precio = new javax.swing.JTextField();
        jTextField2Estado = new javax.swing.JTextField();
        jTextField3Categ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Productos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Productos.setText("CATOLOGO PRODUCTOS");

        jLabel3Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Nombre.setText("Nombre:");

        jLabel4Talla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Talla.setText("Talla:");

        jLabel5Precio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5Precio.setText("Precio:");

        jButton1GuardarProduc.setBackground(new java.awt.Color(204, 204, 204));
        jButton1GuardarProduc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1GuardarProduc.setText("GUARDAR");
        jButton1GuardarProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarProducActionPerformed(evt);
            }
        });

        jLabel6Stock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6Stock.setText("Stock:");

        jLabel7Genero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7Genero.setText("Estado:");

        jLabel8Categoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8Categoria.setText("Categoria:");

        jTextField4Talla.setText(" ");

        jTextField5Precio.setText(" ");

        jTextField2Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EstadoActionPerformed(evt);
            }
        });

        jTextField3Categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3CategActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6Stock)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField1Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5Precio)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField5Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8Categoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3Categ))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7Genero)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4Talla)
                                .addGap(34, 34, 34)
                                .addComponent(jTextField4Talla))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton1GuardarProduc))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1Productos)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1Productos)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jTextField2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Talla)
                    .addComponent(jTextField4Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Stock)
                    .addComponent(jTextField1Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5Precio))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7Genero)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8Categoria)
                        .addComponent(jTextField2Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3Categ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1GuardarProduc)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1GuardarProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarProducActionPerformed
        Productos pro = new Productos();
        pro.setNombre(jTextField2Nom.getText());//obtener texto ingresado
        pro.setTalla(jTextField4Talla.getText());
        try {
            double precio = Double.parseDouble(jTextField5Precio.getText().trim());
            pro.setPrecio(precio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Precio.");
            return; //si el valor no es válido
        }
        try {
            int stock = Integer.parseInt(jTextField1Stock.getText().trim());
            pro.setStock(stock);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido en el campo Stock.");
            return;
        }
        pro.setEstado(jTextField2Estado.getText());
        pro.setCategoria(jTextField3Categ.getText());
        
        if (pro.Guardar()) //variable conexion a BD
            JOptionPane.showMessageDialog(this, "Producto Creado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Producto NO creado", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1GuardarProducActionPerformed

    private void jTextField3CategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3CategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3CategActionPerformed

    private void jTextField2EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2EstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1GuardarProduc;
    private javax.swing.JLabel jLabel1Productos;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Talla;
    private javax.swing.JLabel jLabel5Precio;
    private javax.swing.JLabel jLabel6Stock;
    private javax.swing.JLabel jLabel7Genero;
    private javax.swing.JLabel jLabel8Categoria;
    private javax.swing.JTextField jTextField1Stock;
    private javax.swing.JTextField jTextField2Estado;
    private javax.swing.JTextField jTextField2Nom;
    private javax.swing.JTextField jTextField3Categ;
    private javax.swing.JTextField jTextField4Talla;
    private javax.swing.JTextField jTextField5Precio;
    // End of variables declaration//GEN-END:variables
}
