/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Yefri Chay
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Catologos = new javax.swing.JMenu();
        jMenuItem2Clientes = new javax.swing.JMenuItem();
        jMenuItem1Productos = new javax.swing.JMenuItem();
        jMenuItem4Empleados = new javax.swing.JMenuItem();
        jMenuItem3Inventarios = new javax.swing.JMenuItem();
        jMenu2Operaciones = new javax.swing.JMenu();
        jMenuItem5Facturas = new javax.swing.JMenuItem();
        jMenuItem8Ventas = new javax.swing.JMenuItem();
        jMenu3Consultas = new javax.swing.JMenu();
        jMenuItem6ConsuVentas = new javax.swing.JMenuItem();
        jMenuItem7ConsuInventa = new javax.swing.JMenuItem();
        jMenuItem9ConsuFactu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRM - GRUPO #5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("CRM");

        jMenu1Catologos.setText("Catalogos");

        jMenuItem2Clientes.setText("Clientes");
        jMenuItem2Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ClientesActionPerformed(evt);
            }
        });
        jMenu1Catologos.add(jMenuItem2Clientes);

        jMenuItem1Productos.setText("Productos");
        jMenuItem1Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ProductosActionPerformed(evt);
            }
        });
        jMenu1Catologos.add(jMenuItem1Productos);

        jMenuItem4Empleados.setText("Empleados");
        jMenuItem4Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4EmpleadosActionPerformed(evt);
            }
        });
        jMenu1Catologos.add(jMenuItem4Empleados);

        jMenuItem3Inventarios.setText("Inventarios");
        jMenuItem3Inventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3InventariosActionPerformed(evt);
            }
        });
        jMenu1Catologos.add(jMenuItem3Inventarios);

        jMenuBar1.add(jMenu1Catologos);

        jMenu2Operaciones.setText("Operaciones");

        jMenuItem5Facturas.setText("Facturas");
        jMenuItem5Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5FacturasActionPerformed(evt);
            }
        });
        jMenu2Operaciones.add(jMenuItem5Facturas);

        jMenuItem8Ventas.setText("Ventas");
        jMenuItem8Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8VentasActionPerformed(evt);
            }
        });
        jMenu2Operaciones.add(jMenuItem8Ventas);

        jMenuBar1.add(jMenu2Operaciones);

        jMenu3Consultas.setText("Consultas");

        jMenuItem6ConsuVentas.setText("Ventas");
        jMenuItem6ConsuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ConsuVentasActionPerformed(evt);
            }
        });
        jMenu3Consultas.add(jMenuItem6ConsuVentas);

        jMenuItem7ConsuInventa.setText("Inventarios");
        jMenuItem7ConsuInventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ConsuInventaActionPerformed(evt);
            }
        });
        jMenu3Consultas.add(jMenuItem7ConsuInventa);

        jMenuItem9ConsuFactu.setText("Facturas");
        jMenuItem9ConsuFactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ConsuFactuActionPerformed(evt);
            }
        });
        jMenu3Consultas.add(jMenuItem9ConsuFactu);

        jMenuBar1.add(jMenu3Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("CRM - GRUPO #1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ClientesActionPerformed
        CatClientes c = new CatClientes();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ClientesActionPerformed

    private void jMenuItem1ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ProductosActionPerformed
        CatProductos p = new CatProductos();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ProductosActionPerformed

    private void jMenuItem4EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4EmpleadosActionPerformed
        CatEmpleados e = new CatEmpleados();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }//GEN-LAST:event_jMenuItem4EmpleadosActionPerformed

    private void jMenuItem5FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5FacturasActionPerformed
        OpeFacturas f = new OpeFacturas();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem5FacturasActionPerformed

    private void jMenuItem6ConsuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ConsuVentasActionPerformed
        ConVentas cv = new ConVentas();
        cv.setLocationRelativeTo(null);
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ConsuVentasActionPerformed

    private void jMenuItem7ConsuInventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ConsuInventaActionPerformed
        ConInventarios ci = new ConInventarios();
        ci.setLocationRelativeTo(null);
        ci.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ConsuInventaActionPerformed

    private void jMenuItem3InventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3InventariosActionPerformed
        CatInventarios i = new CatInventarios();
        i.setLocationRelativeTo(null);
        i.setVisible(true);
    }//GEN-LAST:event_jMenuItem3InventariosActionPerformed

    private void jMenuItem8VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8VentasActionPerformed
        OpeVentas v = new OpeVentas();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem8VentasActionPerformed

    private void jMenuItem9ConsuFactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ConsuFactuActionPerformed
        ConFacturas cf = new ConFacturas();
        cf.setLocationRelativeTo(null);
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ConsuFactuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
//    }
        MenuPrincipal mp = new MenuPrincipal();
        mp.setExtendedState(MAXIMIZED_BOTH);
        mp.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1Catologos;
    private javax.swing.JMenu jMenu2Operaciones;
    private javax.swing.JMenu jMenu3Consultas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1Productos;
    private javax.swing.JMenuItem jMenuItem2Clientes;
    private javax.swing.JMenuItem jMenuItem3Inventarios;
    private javax.swing.JMenuItem jMenuItem4Empleados;
    private javax.swing.JMenuItem jMenuItem5Facturas;
    private javax.swing.JMenuItem jMenuItem6ConsuVentas;
    private javax.swing.JMenuItem jMenuItem7ConsuInventa;
    private javax.swing.JMenuItem jMenuItem8Ventas;
    private javax.swing.JMenuItem jMenuItem9ConsuFactu;
    // End of variables declaration//GEN-END:variables
}
