/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Yefri Chay
 */
public class OpeFacturas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OpeFacturas.class.getName());

    /**
     * Creates new form AbcFacturas
     */
    public OpeFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Facturas = new javax.swing.JLabel();
        jLabel2Id = new javax.swing.JLabel();
        jLabel3Fecha = new javax.swing.JLabel();
        jLabel4Metodo = new javax.swing.JLabel();
        jLabel5Total = new javax.swing.JLabel();
        jLabel6IdVentas = new javax.swing.JLabel();
        jTextField1Id = new javax.swing.JTextField();
        jTextField2Fecha = new javax.swing.JTextField();
        jTextField3Metodo = new javax.swing.JTextField();
        jTextField4Total = new javax.swing.JTextField();
        jTextField5IdVen = new javax.swing.JTextField();
        jButton1GenerarFac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Facturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Facturas.setText("OPERACION FACTURAS");

        jLabel2Id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2Id.setText("ID:");

        jLabel3Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Fecha.setText("Fecha Emision:");

        jLabel4Metodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Metodo.setText("Metodo Pago:");

        jLabel5Total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5Total.setText("Total:");

        jLabel6IdVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6IdVentas.setText("ID Venta:");

        jButton1GenerarFac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1GenerarFac.setText("GENERAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton1GenerarFac))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6IdVentas)
                            .addComponent(jLabel5Total)
                            .addComponent(jLabel4Metodo)
                            .addComponent(jLabel3Fecha)
                            .addComponent(jLabel2Id))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1Facturas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2Fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jTextField3Metodo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4Total, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5IdVen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1Id))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1Facturas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Id)
                    .addComponent(jTextField1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Fecha)
                    .addComponent(jTextField2Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Metodo)
                    .addComponent(jTextField3Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Total)
                    .addComponent(jTextField4Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6IdVentas)
                    .addComponent(jTextField5IdVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1GenerarFac)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OpeFacturas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1GenerarFac;
    private javax.swing.JLabel jLabel1Facturas;
    private javax.swing.JLabel jLabel2Id;
    private javax.swing.JLabel jLabel3Fecha;
    private javax.swing.JLabel jLabel4Metodo;
    private javax.swing.JLabel jLabel5Total;
    private javax.swing.JLabel jLabel6IdVentas;
    private javax.swing.JTextField jTextField1Id;
    private javax.swing.JTextField jTextField2Fecha;
    private javax.swing.JTextField jTextField3Metodo;
    private javax.swing.JTextField jTextField4Total;
    private javax.swing.JTextField jTextField5IdVen;
    // End of variables declaration//GEN-END:variables
}
