/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Yefri Chay
 */
public class OpeVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OpeVentas.class.getName());

    /**
     * Creates new form AbcVentas
     */
    public OpeVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Ventas = new javax.swing.JLabel();
        jLabel2Id = new javax.swing.JLabel();
        jLabel3Fecha = new javax.swing.JLabel();
        jLabel4Total = new javax.swing.JLabel();
        jLabel5IdClien = new javax.swing.JLabel();
        jLabel6IdEmple = new javax.swing.JLabel();
        jButton1GenerarVen = new javax.swing.JButton();
        jTextField1Id = new javax.swing.JTextField();
        jTextField2Fecha = new javax.swing.JTextField();
        jTextField4IdClien = new javax.swing.JTextField();
        jTextField5IdEmple = new javax.swing.JTextField();
        jTextField3Total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Ventas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Ventas.setText("OPERACION VENTAS");

        jLabel2Id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2Id.setText("ID:");

        jLabel3Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Fecha.setText("Fecha:");

        jLabel4Total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4Total.setText("Total:");

        jLabel5IdClien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5IdClien.setText("ID Cliente:");

        jLabel6IdEmple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6IdEmple.setText("ID Empleado:");

        jButton1GenerarVen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1GenerarVen.setText("GENERAR VENTA");

        jTextField1Id.setText(" ");

        jTextField2Fecha.setText(" ");

        jTextField4IdClien.setText(" ");

        jTextField5IdEmple.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6IdEmple)
                    .addComponent(jLabel5IdClien)
                    .addComponent(jLabel4Total)
                    .addComponent(jLabel3Fecha)
                    .addComponent(jLabel2Id))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4IdClien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField5IdEmple, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3Total)
                    .addComponent(jTextField1Id)
                    .addComponent(jTextField2Fecha)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1GenerarVen)
                            .addComponent(jLabel1Ventas))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1Ventas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Id)
                    .addComponent(jTextField1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Fecha)
                    .addComponent(jTextField2Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Total)
                    .addComponent(jTextField3Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5IdClien)
                    .addComponent(jTextField4IdClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6IdEmple)
                    .addComponent(jTextField5IdEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1GenerarVen)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OpeVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1GenerarVen;
    private javax.swing.JLabel jLabel1Ventas;
    private javax.swing.JLabel jLabel2Id;
    private javax.swing.JLabel jLabel3Fecha;
    private javax.swing.JLabel jLabel4Total;
    private javax.swing.JLabel jLabel5IdClien;
    private javax.swing.JLabel jLabel6IdEmple;
    private javax.swing.JTextField jTextField1Id;
    private javax.swing.JTextField jTextField2Fecha;
    private javax.swing.JTextField jTextField3Total;
    private javax.swing.JTextField jTextField4IdClien;
    private javax.swing.JTextField jTextField5IdEmple;
    // End of variables declaration//GEN-END:variables
}
